server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
  mail:
    host: smtpout.secureserver.net
    port: 465
    username: info@hubapp.co.in
    password: Info@Hub12345
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.trust: "*"  

logging:
  level:
    root: WARN
    in.co.hubapp: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
 

   
    
 